<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Placements</name>
   <tag></tag>
   <elementGuidId>9c75dd6a-a6f0-4b9c-90be-3592a5dd4e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.collapse-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebarMasterData']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a709911d-529e-4d72-a349-d71fb2e30f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapse-item</value>
      <webElementGuid>9d2920c8-df7b-439e-a1be-1a5fe8316021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://career.vasdev.co.id/admin/master/placement</value>
      <webElementGuid>34b671f8-c6ca-4e57-8c7c-8143a02b5a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Placements
                </value>
      <webElementGuid>833a28b2-2847-4967-9ebd-45c2d950c8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarMasterData&quot;)/div[@class=&quot;bg-white py-2 collapse-inner rounded&quot;]/a[@class=&quot;collapse-item&quot;]</value>
      <webElementGuid>c68023a8-4867-4a3c-9b47-287b5e7c57b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarMasterData']/div/a</value>
      <webElementGuid>b7d701a1-9f19-4421-bc5a-41b4c3ef37e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Placements')]</value>
      <webElementGuid>8b0770d7-8557-49e4-ad03-4eaba7cacdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data:'])[1]/following::a[1]</value>
      <webElementGuid>abe31ad6-9bcd-4a05-9345-106196c88560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::a[1]</value>
      <webElementGuid>5d0308b7-b894-442e-91a6-6c2449e6865e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contracts'])[1]/preceding::a[1]</value>
      <webElementGuid>cb7031d0-71b1-4445-b3d9-a4f4e1b84c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Educations'])[1]/preceding::a[2]</value>
      <webElementGuid>ae9baa9c-02f3-4ef3-b943-6909a91d21ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Placements']/parent::*</value>
      <webElementGuid>02b26f96-e15b-4451-a816-c0671df8573d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://career.vasdev.co.id/admin/master/placement')]</value>
      <webElementGuid>3967b243-8b9b-4a28-a263-1f5315e85b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>ec669907-9b21-4bc0-8f15-9b9c4f0450c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://career.vasdev.co.id/admin/master/placement' and (text() = '
                    Placements
                ' or . = '
                    Placements
                ')]</value>
      <webElementGuid>7e02d7df-cdc3-42fd-aaba-b3d8a810370d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
